(() => {
  'use strict';

  const EVENT_ID='333mbf';
  const HISTORY_KEY='rubiksCubeTimerHistoryV1';
  const ATTEMPTED_KEY='sscMbldAttemptedV2';
  const LIMIT_MS=60*60*1000;
  const MIN_CUBES=2;
  const MAX_CUBES=100;
  const HOLD_MS=500;

  const els={timer:document.getElementById('timer'),status:document.getElementById('status'),touchTimer:document.getElementById('touchTimer'),eventSelect:document.getElementById('eventSelect'),sessionSelect:document.getElementById('sessionSelect'),newScramble:document.getElementById('newScramble'),prevScramble:document.getElementById('prevScramble'),scramble:document.getElementById('scramble'),scrambleLabel:document.getElementById('scrambleLabel'),preview:document.getElementById('cubePreview2D'),statsGrid:document.getElementById('statsGrid'),historyList:document.getElementById('historyList'),emptyHistory:document.getElementById('emptyHistory'),solveCount:document.getElementById('solveCount'),quickStats:document.querySelector('.quick-stats'),scrambleBar:document.querySelector('.scramble-bar'),scrambleCenter:document.querySelector('.scramble-center')};
  if(!els.timer||!els.status||!els.touchTimer||!els.scramble||!els.scrambleCenter)return;

  let attempted=readAttempted(),phase='inactive',generatedScrambles=[],currentScramble='',startTime=0,totalTime=null,frame=null,holdTimer=null,pointerId=null,summaryWrite=false,modalObserver=null,countSyncPending=false;

  function isEnglish(){return document.documentElement.lang==='en'||document.documentElement.dir==='ltr';}
  function text(he,en){return isEnglish()?en:he;}
  function currentEvent(){return window.SSCTimerEvents?.getCurrent?.()||els.eventSelect?.value||'';}
  function isMbld(){return currentEvent()===EVENT_ID;}
  function isEditableTarget(target){return Boolean(target?.closest?.('input,textarea,select,[contenteditable="true"]'));}
  function clampInt(value,min,max,fallback=min){const parsed=Number.parseInt(value,10);if(!Number.isInteger(parsed))return fallback;return Math.min(max,Math.max(min,parsed));}
  function readAttempted(){return clampInt(localStorage.getItem(ATTEMPTED_KEY),MIN_CUBES,MAX_CUBES,3);}
  function writeAttempted(value){attempted=clampInt(value,MIN_CUBES,MAX_CUBES,3);localStorage.setItem(ATTEMPTED_KEY,String(attempted));syncCountControl();return attempted;}
  function roundMs(value){return Math.max(0,Math.round(Number(value)||0));}
  function readPrecision(){try{return Number(JSON.parse(localStorage.getItem('sscGeneralSettingsV1'))?.timePrecision)===2?2:3;}catch{return 3;}}
  function formatTimer(ms){return(roundMs(ms)/1000).toFixed(readPrecision());}
  function formatClock(ms){const safe=roundMs(ms),seconds=Math.floor(safe/1000),hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60),secs=seconds%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`:`${minutes}:${String(secs).padStart(2,'0')}`;}
  function calculateResult({attempted:attemptedValue,solved:solvedValue,totalTime:timeValue}){const attemptedCount=clampInt(attemptedValue,MIN_CUBES,MAX_CUBES,MIN_CUBES),solvedCount=clampInt(solvedValue,0,attemptedCount,0),total=roundMs(timeValue),points=solvedCount-(attemptedCount-solvedCount),isDNF=points<1||solvedCount<2||total>LIMIT_MS,core=`${solvedCount}/${attemptedCount} ${formatClock(total)}`;return Object.freeze({attempted:attemptedCount,solved:solvedCount,points,isDNF,totalTime:total,memoTime:null,displayResult:isDNF?`DNF (${core})`:core});}

  function injectStyles(){if(document.getElementById('sscMbldRegularFlowStyles'))return;const style=document.createElement('style');style.id='sscMbldRegularFlowStyles';style.textContent=`
    .scramble-bar.ssc-mbld-active{grid-template-columns:42px minmax(0,1fr) 46px!important}.scramble-bar.ssc-mbld-active .scramble-side{width:46px!important;min-width:46px!important}.scramble-bar.ssc-mbld-active #cubePreview2D{display:none!important}.scramble-bar.ssc-mbld-active #prevScramble{visibility:hidden!important}
    .ssc-mbld-title-row{display:flex;align-items:center;justify-content:center;gap:10px;min-width:0;margin-bottom:5px}.ssc-mbld-title-row .scramble-title{margin:0!important}.ssc-mbld-count-control{display:none;align-items:center;gap:5px;padding:3px 6px;border:1px solid var(--border);border-radius:999px;background:var(--soft);color:var(--text);font-size:11px;font-weight:800;white-space:nowrap}.scramble-bar.ssc-mbld-active .ssc-mbld-count-control{display:inline-flex}.ssc-mbld-count-control button{width:22px;height:22px;border:0;border-radius:50%;background:var(--card-solid,#fff);color:var(--text);font:inherit;font-size:16px;line-height:1;cursor:pointer}.ssc-mbld-count-control input{width:40px;border:0;background:transparent;color:var(--text);font:inherit;font-size:12px;font-weight:900;text-align:center;appearance:textfield;-moz-appearance:textfield}.ssc-mbld-count-control input::-webkit-inner-spin-button,.ssc-mbld-count-control input::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}
    #scramble.ssc-mbld-summary{cursor:pointer!important;display:flex!important;align-items:center;justify-content:center;gap:9px;min-height:38px;font-size:clamp(15px,1.35vw,20px)!important;word-spacing:normal!important;user-select:none}#scramble.ssc-mbld-summary:hover{color:var(--accent)}.ssc-mbld-summary-badge{display:inline-grid;place-items:center;min-width:28px;height:28px;padding:0 7px;border-radius:999px;background:color-mix(in srgb,var(--accent) 13%,var(--soft));color:var(--accent);font-size:12px;font-weight:900}
    .ssc-mbld-modal[hidden]{display:none!important}.ssc-mbld-modal{position:fixed;inset:0;z-index:13000;display:grid;place-items:center;padding:18px}.ssc-mbld-backdrop{position:absolute;inset:0;background:rgba(8,15,30,.66);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px)}.ssc-mbld-dialog{position:relative;z-index:1;width:min(94vw,980px);max-height:90dvh;display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden;border:1px solid color-mix(in srgb,var(--border) 82%,var(--accent) 18%);border-radius:22px;background:var(--card-solid,#fff);color:var(--text);box-shadow:0 30px 90px rgba(0,0,0,.34)}.ssc-mbld-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 18px;border-bottom:1px solid var(--border);background:linear-gradient(135deg,color-mix(in srgb,var(--accent) 9%,var(--card-solid,#fff)),var(--card-solid,#fff) 58%)}.ssc-mbld-dialog-title{display:flex;align-items:center;gap:10px;min-width:0}.ssc-mbld-dialog-kicker{padding:5px 8px;border-radius:8px;background:var(--accent);color:#fff;font-size:10px;font-weight:900;letter-spacing:.1em}.ssc-mbld-dialog-title h2{margin:0;font-size:20px}.ssc-mbld-dialog-title p{margin:2px 0 0;color:var(--muted);font-size:12px}.ssc-mbld-close{width:34px;height:34px;border:1px solid var(--border);border-radius:10px;background:var(--soft);color:var(--text);font:inherit;font-size:20px;cursor:pointer}
    .ssc-mbld-scramble-scroll{overflow:auto;padding:14px;scrollbar-gutter:stable;background:color-mix(in srgb,var(--soft) 62%,transparent)}.ssc-mbld-view-list{display:grid;gap:10px;direction:ltr}.ssc-mbld-view-row{position:relative;display:grid;grid-template-columns:48px minmax(0,1fr) 132px;align-items:center;gap:12px;padding:11px 12px;border:1px solid var(--border);border-radius:15px;background:var(--card-solid,#fff);overflow:hidden}.ssc-mbld-view-row::before{content:'';position:absolute;inset-block:0;inset-inline-start:0;width:3px;background:var(--accent);opacity:.72}.ssc-mbld-view-number{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:var(--soft);color:var(--accent);font-family:'Share Tech Mono',monospace;font-size:14px;font-weight:900}.ssc-mbld-view-text{direction:ltr;unicode-bidi:plaintext;text-align:left;min-width:0;font-family:'Share Tech Mono',ui-monospace,monospace;font-size:clamp(13px,1.05vw,16px);font-weight:700;line-height:1.48;word-spacing:3px;overflow-wrap:anywhere}.ssc-mbld-view-preview.cube-preview-card{width:116px!important;min-width:116px!important;max-width:116px!important;height:76px!important;min-height:76px!important;max-height:76px!important;padding:7px!important;margin:0!important;justify-self:end!important;pointer-events:none!important;cursor:default!important}.ssc-mbld-view-preview[data-pending="true"]::before{content:'3×3';color:var(--muted);font-size:11px;font-weight:900}
    .ssc-mbld-result-dialog{width:min(92vw,430px);grid-template-rows:auto auto}.ssc-mbld-result-body{padding:18px;display:grid;gap:14px}.ssc-mbld-result-time{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ssc-mbld-result-time>div{padding:10px;border:1px solid var(--border);border-radius:11px;background:var(--soft);text-align:center}.ssc-mbld-result-time span{display:block;color:var(--muted);font-size:11px;font-weight:800}.ssc-mbld-result-time strong{display:block;margin-top:4px;font-size:17px}.ssc-mbld-result-field{display:grid;gap:7px}.ssc-mbld-result-field span{font-size:13px;font-weight:800;color:var(--muted)}.ssc-mbld-result-field input{width:100%;box-sizing:border-box;border:1px solid var(--border);border-radius:12px;background:var(--soft);color:var(--text);font:inherit;font-size:28px;font-weight:900;padding:10px;text-align:center}.ssc-mbld-result-preview{padding:11px;border-radius:11px;background:var(--soft);text-align:center;font-weight:900}.ssc-mbld-result-preview.dnf{color:#dc2626}.ssc-mbld-result-actions{display:flex;justify-content:flex-end;gap:8px;padding:0 18px 18px}.ssc-mbld-result-actions button{border:1px solid var(--border);border-radius:10px;background:var(--soft);color:var(--text);font:inherit;font-weight:800;padding:9px 13px;cursor:pointer}.ssc-mbld-result-actions .primary{background:var(--accent);border-color:var(--accent);color:#fff}
    .ssc-mbld-history-row .solve-time{font-size:16px;font-weight:900}.ssc-mbld-history-row .solve-meta{white-space:normal}.ssc-mbld-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ssc-mbld-stat{border:1px solid var(--border);border-radius:10px;padding:9px;background:var(--soft);text-align:center}.ssc-mbld-stat span{display:block;color:var(--muted);font-size:11px;font-weight:800}.ssc-mbld-stat strong{display:block;margin-top:3px}html[dir="rtl"] .ssc-mbld-result-dialog{text-align:right}
    @media(max-width:680px){.ssc-mbld-modal{padding:8px}.ssc-mbld-dialog{width:100%;max-height:94dvh;border-radius:16px}.ssc-mbld-view-row{grid-template-columns:38px minmax(0,1fr);gap:8px}.ssc-mbld-view-preview.cube-preview-card{grid-column:2;justify-self:start!important}.ssc-mbld-dialog-title h2{font-size:17px}.ssc-mbld-title-row{gap:6px}.ssc-mbld-count-control{padding:2px 4px}}
  `;document.head.appendChild(style);}

  function ensureTitleRow(){let row=document.getElementById('sscMbldTitleRow');if(row)return row;row=document.createElement('div');row.id='sscMbldTitleRow';row.className='ssc-mbld-title-row';els.scrambleLabel.insertAdjacentElement('beforebegin',row);row.appendChild(els.scrambleLabel);const control=document.createElement('div');control.id='sscMbldCountControl';control.className='ssc-mbld-count-control';control.innerHTML=`<span data-count-label></span><button type="button" data-count-minus aria-label="-">−</button><input id="sscMbldCount" type="number" min="${MIN_CUBES}" max="${MAX_CUBES}" step="1" inputmode="numeric"><button type="button" data-count-plus aria-label="+">+</button>`;row.appendChild(control);const input=control.querySelector('#sscMbldCount');const commit=()=>{const next=writeAttempted(input.value);input.value=String(next);regenerateForCount();};input.addEventListener('change',commit);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.blur();}});control.querySelector('[data-count-minus]').addEventListener('click',()=>{input.value=String(writeAttempted(attempted-1));regenerateForCount();});control.querySelector('[data-count-plus]').addEventListener('click',()=>{input.value=String(writeAttempted(attempted+1));regenerateForCount();});return row;}
  function syncCountControl(){ensureTitleRow();const input=document.getElementById('sscMbldCount');if(input)input.value=String(attempted);const label=document.querySelector('#sscMbldCountControl [data-count-label]');if(label)label.textContent=text('קוביות','cubes');}

  function ensureScrambleModal(){let modal=document.getElementById('sscMbldScramblesModal');if(modal)return modal;modal=document.createElement('div');modal.id='sscMbldScramblesModal';modal.className='ssc-mbld-modal';modal.hidden=true;modal.innerHTML=`<div class="ssc-mbld-backdrop" data-close-mbld-view></div><section class="ssc-mbld-dialog" role="dialog" aria-modal="true" aria-labelledby="sscMbldViewTitle"><header class="ssc-mbld-dialog-head"><div class="ssc-mbld-dialog-title"><span class="ssc-mbld-dialog-kicker">MBLD</span><div><h2 id="sscMbldViewTitle"></h2><p id="sscMbldViewSubtitle"></p></div></div><button class="ssc-mbld-close" type="button" data-close-mbld-view aria-label="Close">×</button></header><div class="ssc-mbld-scramble-scroll"><div id="sscMbldViewList" class="ssc-mbld-view-list"></div></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close-mbld-view]').forEach(el=>el.addEventListener('click',closeScrambleModal));return modal;}
  function disposeModalPreviews(){document.querySelectorAll('#sscMbldViewList .ssc-mbld-view-preview').forEach(card=>{window.SSCPuzzle3D?.dispose?.(card);card.replaceChildren();});modalObserver?.disconnect?.();modalObserver=null;}
  function closeScrambleModal(){const modal=ensureScrambleModal();modal.hidden=true;disposeModalPreviews();}
  async function renderPreview(card){if(!(card instanceof Element)||card.dataset.rendered==='true')return;const scramble=card.dataset.scramble||'';if(!scramble)return;card.dataset.rendered='true';card.dataset.pending='false';try{await Promise.resolve(window.SSCCubePreview?.render?.(card,scramble,'333'));window.SSCPreviewSizing?.scheduleFit?.(card);}catch(error){console.error('[SSC MBLD] Preview failed.',error);card.dataset.error='true';}}
  function scheduleModalPreviews(list,cards){modalObserver?.disconnect?.();cards.slice(0,4).forEach(renderPreview);const rest=cards.slice(4);if(!rest.length)return;if(!('IntersectionObserver'in window)){rest.forEach(renderPreview);return;}const root=list.closest('.ssc-mbld-scramble-scroll');modalObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;renderPreview(entry.target);modalObserver?.unobserve?.(entry.target);});},{root,rootMargin:'180px 0px'});rest.forEach(card=>modalObserver.observe(card));}
  function renderScrambleModal(){const modal=ensureScrambleModal(),list=modal.querySelector('#sscMbldViewList');disposeModalPreviews();list.replaceChildren();modal.querySelector('#sscMbldViewTitle').textContent=text('ערבובי MBLD','MBLD scrambles');modal.querySelector('#sscMbldViewSubtitle').textContent=text(`${generatedScrambles.length} קוביות · התצוגה זהה ל־3×3 שנבחרה בהגדרות`,`${generatedScrambles.length} cubes · previews use your selected 3×3 view`);const cards=[],fragment=document.createDocumentFragment();generatedScrambles.forEach((scramble,index)=>{const row=document.createElement('article');row.className='ssc-mbld-view-row';const number=document.createElement('div');number.className='ssc-mbld-view-number';number.textContent=String(index+1);const textEl=document.createElement('div');textEl.className='ssc-mbld-view-text';textEl.textContent=scramble;const preview=document.createElement('div');preview.className='cube-preview-card ssc-mbld-view-preview';preview.dataset.scramble=scramble;preview.dataset.pending='true';preview.setAttribute('aria-label',`3x3 preview ${index+1}`);row.append(number,textEl,preview);fragment.appendChild(row);cards.push(preview);});list.appendChild(fragment);scheduleModalPreviews(list,cards);}
  function openScrambleModal(){if(!isMbld()||!generatedScrambles.length||['holding','ready','running','post'].includes(phase))return;const modal=ensureScrambleModal();renderScrambleModal();modal.hidden=false;}

  function ensureResultModal(){let modal=document.getElementById('sscMbldResultModal');if(modal)return modal;modal=document.createElement('div');modal.id='sscMbldResultModal';modal.className='ssc-mbld-modal';modal.hidden=true;modal.innerHTML=`<div class="ssc-mbld-backdrop"></div><section class="ssc-mbld-dialog ssc-mbld-result-dialog" role="dialog" aria-modal="true" aria-labelledby="sscMbldResultTitle"><header class="ssc-mbld-dialog-head"><div class="ssc-mbld-dialog-title"><span class="ssc-mbld-dialog-kicker">RESULT</span><div><h2 id="sscMbldResultTitle"></h2><p id="sscMbldResultSubtitle"></p></div></div></header><div><div class="ssc-mbld-result-body"><div class="ssc-mbld-result-time"><div><span data-total-label></span><strong data-total-time></strong></div><div><span data-attempted-label></span><strong data-attempted></strong></div></div><label class="ssc-mbld-result-field"><span data-solved-label></span><input id="sscMbldSolved" type="number" min="0" step="1" inputmode="numeric"></label><div class="ssc-mbld-result-preview" data-result-preview></div></div><div class="ssc-mbld-result-actions"><button type="button" data-discard></button><button type="button" class="primary" data-save></button></div></div></section>`;document.body.appendChild(modal);const input=modal.querySelector('#sscMbldSolved');input.addEventListener('input',updateResultPreview);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();saveResult();}});modal.querySelector('[data-save]').addEventListener('click',saveResult);modal.querySelector('[data-discard]').addEventListener('click',discardResult);return modal;}
  function syncResultLabels(){const modal=ensureResultModal();modal.querySelector('#sscMbldResultTitle').textContent=text('כמה קוביות נפתרו?','How many cubes were solved?');modal.querySelector('#sscMbldResultSubtitle').textContent=text('הזן את מספר הקוביות שהושלמו בהצלחה.','Enter the number of cubes solved successfully.');modal.querySelector('[data-total-label]').textContent=text('זמן','Time');modal.querySelector('[data-attempted-label]').textContent=text('ניסיון','Attempted');modal.querySelector('[data-solved-label]').textContent=text('נפתרו בהצלחה','Solved successfully');modal.querySelector('[data-discard]').textContent=text('בטל ניסיון','Discard');modal.querySelector('[data-save]').textContent=text('שמור תוצאה','Save result');}
  function resultFromModal(){const input=ensureResultModal().querySelector('#sscMbldSolved');return calculateResult({attempted,solved:input.value,totalTime});}
  function updateResultPreview(){const modal=ensureResultModal(),result=resultFromModal(),preview=modal.querySelector('[data-result-preview]');preview.classList.toggle('dnf',result.isDNF);preview.textContent=`${result.displayResult} · ${text('נקודות','points')}: ${result.points}`;}
  function openResultModal(){syncResultLabels();const modal=ensureResultModal();modal.querySelector('[data-total-time]').textContent=formatClock(totalTime||0);modal.querySelector('[data-attempted]').textContent=String(attempted);const input=modal.querySelector('#sscMbldSolved');input.max=String(attempted);input.value=String(attempted);modal.hidden=false;updateResultPreview();requestAnimationFrame(()=>{input.focus();input.select();});}

  function readJson(key,fallback){try{const parsed=JSON.parse(localStorage.getItem(key));return parsed??fallback;}catch{return fallback;}}
  function currentSessionId(){return window.SSCTimerEvents?.getCurrentSession?.()?.id||els.sessionSelect?.value||`${EVENT_ID}-session`;}
  function resultRecord(result){const createdAt=new Date().toISOString(),sessionId=currentSessionId(),id=crypto.randomUUID?crypto.randomUUID():`mbld-${Date.now()}-${Math.random()}`;return{id,event:'mbld',eventId:EVENT_ID,totalTime:result.totalTime,memoTime:null,attempted:result.attempted,solved:result.solved,points:result.points,isDNF:result.isDNF,displayResult:result.displayResult,timeMs:result.totalTime,rawTimeMs:result.totalTime,rawTime:result.totalTime/1000,penalty:result.isDNF?'DNF':'OK',finalTimeMs:result.isDNF?null:result.totalTime,finalTime:result.isDNF?null:result.totalTime/1000,scramble:currentScramble,scrambles:[...generatedScrambles],puzzle:'333mbf',puzzleId:'3x3x3',sessionId,session:sessionId,createdAt,date:createdAt,mbld:true};}
  function saveRecord(record){const history=readJson(HISTORY_KEY,[]),safe=Array.isArray(history)?history:[];localStorage.setItem(HISTORY_KEY,JSON.stringify([record,...safe.filter(item=>item?.id!==record.id)]));return record;}
  function saveResult(){if(phase!=='post')return null;const result=resultFromModal(),record=saveRecord(resultRecord(result));ensureResultModal().hidden=true;phase='idle';setControlsLocked(false);els.timer.textContent=result.isDNF?'DNF':formatTimer(result.totalTime);els.timer.className='';els.status.textContent=text('תוצאת MBLD נשמרה','MBLD result saved');renderMbldHistory();window.dispatchEvent(new CustomEvent('ssc-mbld-result-saved',{detail:{...record}}));window.SSCTimerEvents?.newScramble?.();return record;}
  function discardResult(){if(phase!=='post')return;ensureResultModal().hidden=true;phase='idle';setControlsLocked(false);els.timer.className='';els.status.textContent=text('הניסיון לא נשמר','Attempt discarded');window.SSCTimerEvents?.newScramble?.();}
  function mbldHistory(){const sessionId=currentSessionId(),history=readJson(HISTORY_KEY,[]);return(Array.isArray(history)?history:[]).filter(item=>(item?.eventId===EVENT_ID||item?.event==='mbld')&&item?.sessionId===sessionId);}
  function normalizeStored(item){if(!Number.isFinite(Number(item?.attempted))||!Number.isFinite(Number(item?.solved)))return null;const calculated=calculateResult({attempted:item.attempted,solved:item.solved,totalTime:item.totalTime??item.timeMs});return{...item,...calculated,displayResult:item.displayResult||calculated.displayResult};}
  function renderMbldHistory(){if(!isMbld())return;const history=mbldHistory().map(normalizeStored).filter(Boolean);if(els.solveCount)els.solveCount.textContent=String(history.length);if(els.emptyHistory){els.emptyHistory.textContent=text('עדיין אין ניסיונות MBLD שמורים.','No saved MBLD attempts yet.');els.emptyHistory.hidden=history.length>0;}if(els.historyList){els.historyList.innerHTML='';els.historyList.hidden=history.length===0;history.slice(0,12).forEach((solve,index)=>{const row=document.createElement('div');row.className='solve-row enhanced-solve-row ssc-mbld-history-row'+(solve.isDNF?' penalty-dnf':'');const date=new Date(solve.createdAt||solve.date);row.innerHTML=`<div class="solve-index">${index+1}</div><div class="solve-main"><div class="solve-time"></div><div class="solve-meta"></div></div>`;row.querySelector('.solve-time').textContent=solve.displayResult;row.querySelector('.solve-meta').textContent=`${date.toLocaleString(isEnglish()?'en-US':'he-IL',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})} · ${text('נקודות','Points')} ${solve.points}`;els.historyList.appendChild(row);});}if(els.statsGrid){const valid=history.filter(item=>!item.isDNF).sort((a,b)=>b.points-a.points||a.totalTime-b.totalTime),best=valid[0]||null;els.statsGrid.innerHTML=`<div class="ssc-mbld-stats"><div class="ssc-mbld-stat"><span>${text('התוצאה הטובה ביותר','Best result')}</span><strong>${best?`${best.solved}/${best.attempted} · ${best.points} ${text('נק׳','pts')}`:'—'}</strong></div><div class="ssc-mbld-stat"><span>${text('ניסיונות','Attempts')}</span><strong>${history.length}</strong></div></div>`;}if(els.quickStats)els.quickStats.hidden=true;}

  function clearRunFrame(){if(frame!==null)cancelAnimationFrame(frame);frame=null;}function clearHold(){if(holdTimer!==null)clearTimeout(holdTimer);holdTimer=null;}
  function setControlsLocked(locked){if(els.eventSelect)els.eventSelect.disabled=Boolean(locked);if(els.sessionSelect)els.sessionSelect.disabled=Boolean(locked);if(els.newScramble)els.newScramble.disabled=Boolean(locked);const input=document.getElementById('sscMbldCount');if(input)input.disabled=Boolean(locked);document.querySelectorAll('#sscMbldCountControl button').forEach(button=>button.disabled=Boolean(locked));}
  function idleStatus(){els.status.textContent=text('החזק Space, המתן לירוק ושחרר להתחלה','Hold Space, wait for green, then release to start');els.touchTimer.textContent=text('החזק כאן להפעלה','Hold here to start');}
  function startHolding(){if(phase!=='idle'||!generatedScrambles.length)return false;closeScrambleModal();phase='holding';els.timer.className='holding';els.status.textContent=text('המשך להחזיק...','Keep holding...');clearHold();holdTimer=setTimeout(()=>{if(phase!=='holding')return;phase='ready';els.timer.className='ready';els.status.textContent=text('מוכן — שחרר להתחלה','Ready — release to start');},HOLD_MS);return true;}
  function cancelHolding(){if(phase!=='holding'&&phase!=='ready')return;clearHold();phase='idle';els.timer.className='';idleStatus();}
  function startRunning(){if(phase!=='ready')return;clearHold();phase='running';startTime=performance.now();totalTime=null;setControlsLocked(true);els.timer.className='running';els.timer.textContent=(0).toFixed(readPrecision());els.status.textContent=text('Space לעצירה','Space to stop');els.touchTimer.textContent=text('עצור','STOP');tick();}
  function tick(){if(phase!=='running')return;els.timer.textContent=formatTimer(performance.now()-startTime);frame=requestAnimationFrame(tick);}
  function stopRunning(){if(phase!=='running')return false;totalTime=roundMs(performance.now()-startTime);clearRunFrame();phase='post';els.timer.className='';els.timer.textContent=formatTimer(totalTime);els.status.textContent=text('הזן כמה קוביות נפתרו','Enter how many cubes were solved');els.touchTimer.textContent='';setControlsLocked(true);openResultModal();return true;}

  function parseMultiText(value){const textValue=String(value||'').trim();if(!/^1\)\s/.test(textValue))return[];return textValue.split(/\s*\|\s*/).map(part=>part.replace(/^\d+\)\s*/,'').trim()).filter(Boolean);}
  function rawScrambleText(scrambles=generatedScrambles){return scrambles.map((value,index)=>`${index+1}) ${value}`).join(' | ');}
  function renderSummary(){if(!isMbld()||!generatedScrambles.length)return;summaryWrite=true;els.scramble.dataset.scrambleTransient='true';els.scramble.dataset.eventId=EVENT_ID;els.scramble.classList.add('ssc-mbld-summary');els.scramble.setAttribute('role','button');els.scramble.tabIndex=0;els.scramble.innerHTML=`<span class="ssc-mbld-summary-badge">${generatedScrambles.length}</span><span>${text('ערבובי MBLD · לחץ לצפייה','MBLD scrambles · click to view')}</span>`;if(els.scrambleLabel)els.scrambleLabel.textContent='MBLD';queueMicrotask(()=>{summaryWrite=false;});}
  function captureGeneratedScrambles(){if(summaryWrite||!isMbld()||els.scramble.dataset.scrambleTransient==='true')return;const parsed=parseMultiText(els.scramble.textContent);if(!parsed.length)return;generatedScrambles=parsed;currentScramble=rawScrambleText(parsed);window.dispatchEvent(new CustomEvent('ssc-mbld-scramble',{detail:{attempted:parsed.length,scrambles:[...parsed],scramble:currentScramble}}));renderSummary();if(parsed.length!==attempted&&!countSyncPending){countSyncPending=true;setTimeout(()=>{countSyncPending=false;if(isMbld()&&generatedScrambles.length!==attempted)window.SSCTimerEvents?.newScramble?.();},0);}}
  function regenerateForCount(){if(!isMbld()||phase!=='idle')return;generatedScrambles=[];currentScramble='';els.scramble.classList.remove('ssc-mbld-summary');els.scramble.dataset.scrambleTransient='true';els.scramble.textContent=text('יוצר ערבובים…','Generating scrambles…');window.SSCTimerEvents?.newScramble?.();}
  function installScrambleCountBridge(){const provider=window.SSCScrambles;if(!provider||provider.__sscMbldCountBridge||typeof provider.generateMultiBlind!=='function')return;const baseGenerate=provider.generateMultiBlind.bind(provider),bridge=Object.freeze({...provider,__sscMbldCountBridge:true,generateMultiBlind:count=>baseGenerate(isMbld()?attempted:count)});window.SSCScrambles=bridge;if(window.SSCScrambleProvider===provider)window.SSCScrambleProvider=bridge;}

  function activate(){injectStyles();ensureTitleRow();ensureScrambleModal();ensureResultModal();syncCountControl();phase=phase==='inactive'?'idle':phase;els.scrambleBar?.classList.add('ssc-mbld-active');if(els.preview)els.preview.hidden=true;if(els.prevScramble)els.prevScramble.hidden=true;if(els.quickStats)els.quickStats.hidden=true;setControlsLocked(false);idleStatus();renderMbldHistory();setTimeout(captureGeneratedScrambles,0);}
  function deactivate(){clearHold();clearRunFrame();phase='inactive';pointerId=null;closeScrambleModal();ensureResultModal().hidden=true;els.scrambleBar?.classList.remove('ssc-mbld-active');els.scramble.classList.remove('ssc-mbld-summary');els.scramble.removeAttribute('role');els.scramble.removeAttribute('tabindex');if(els.preview)els.preview.hidden=false;if(els.prevScramble)els.prevScramble.hidden=false;if(els.quickStats)els.quickStats.hidden=false;setControlsLocked(false);}
  function interceptKeyDown(event){if(!isMbld())return;if(event.code==='Space'&&isEditableTarget(event.target))return;if(event.code==='Space'){event.preventDefault();event.stopImmediatePropagation();if(event.repeat)return;if(!ensureScrambleModal().hidden){closeScrambleModal();return;}if(phase==='running'){stopRunning();return;}if(phase==='idle')startHolding();return;}if(['holding','ready','running','post'].includes(phase)&&(event.ctrlKey||event.metaKey)){event.preventDefault();event.stopImmediatePropagation();}}
  function interceptKeyUp(event){if(!isMbld()||event.code!=='Space'||isEditableTarget(event.target))return;event.preventDefault();event.stopImmediatePropagation();if(phase==='ready')startRunning();else if(phase==='holding')cancelHolding();}
  document.addEventListener('keydown',interceptKeyDown,true);document.addEventListener('keyup',interceptKeyUp,true);
  function pointerDown(event){if(!isMbld())return;event.preventDefault();event.stopImmediatePropagation();if(phase==='running'){stopRunning();return;}if(phase!=='idle')return;pointerId=event.pointerId;els.touchTimer.setPointerCapture?.(event.pointerId);startHolding();}
  function pointerUp(event){if(!isMbld())return;event.preventDefault();event.stopImmediatePropagation();if(pointerId!==null&&event.pointerId!==pointerId)return;pointerId=null;if(phase==='ready')startRunning();else if(phase==='holding')cancelHolding();}
  function pointerCancel(event){if(!isMbld())return;event.preventDefault();event.stopImmediatePropagation();pointerId=null;cancelHolding();}
  els.touchTimer.addEventListener('pointerdown',pointerDown,true);els.touchTimer.addEventListener('pointerup',pointerUp,true);els.touchTimer.addEventListener('pointercancel',pointerCancel,true);
  els.scramble.addEventListener('click',event=>{if(!isMbld())return;event.preventDefault();event.stopImmediatePropagation();openScrambleModal();},true);els.scramble.addEventListener('keydown',event=>{if(!isMbld()||(event.key!=='Enter'&&event.key!==' '))return;event.preventDefault();event.stopImmediatePropagation();openScrambleModal();},true);els.sessionSelect?.addEventListener('change',()=>queueMicrotask(renderMbldHistory));

  const scrambleObserver=new MutationObserver(captureGeneratedScrambles);scrambleObserver.observe(els.scramble,{childList:true,characterData:true,subtree:true});const languageObserver=new MutationObserver(()=>{if(isMbld()){syncCountControl();renderSummary();syncResultLabels();if(!ensureScrambleModal().hidden)renderScrambleModal();}});languageObserver.observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir']});const rerenderOpenModal=()=>{if(isMbld()&&!ensureScrambleModal().hidden)renderScrambleModal();};window.addEventListener('ssc-preview-mode-change',rerenderOpenModal);window.addEventListener('ssc-selected-faces-mode-change',rerenderOpenModal);window.addEventListener('ssc-general-settings-change',rerenderOpenModal);window.addEventListener('ssc-event-change',event=>{const eventId=event.detail?.eventId||currentEvent();if(eventId===EVENT_ID)activate();else deactivate();});

  const nativeSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(this===localStorage&&key===HISTORY_KEY&&window.SSCMBLD){try{const incoming=JSON.parse(value),existing=JSON.parse(this.getItem(key));if(Array.isArray(incoming)&&Array.isArray(existing)){const mbld=existing.filter(item=>item?.mbld===true||item?.event==='mbld'),ids=new Set(incoming.map(item=>item?.id).filter(Boolean));return nativeSetItem.call(this,key,JSON.stringify([...incoming,...mbld.filter(item=>!ids.has(item?.id))]));}}catch{}}return nativeSetItem.call(this,key,value);};

  injectStyles();installScrambleCountBridge();ensureTitleRow();ensureScrambleModal();ensureResultModal();syncCountControl();window.SSCMBLD=Object.freeze({version:'2.0.0',LIMIT_MS,getPhase:()=>phase,getAttempted:()=>attempted,setAttempted:value=>{const next=writeAttempted(value);regenerateForCount();return next;},getScrambles:()=>[...generatedScrambles],calculateResult,formatClock,openScrambles:openScrambleModal,renderHistory:renderMbldHistory});queueMicrotask(()=>{if(isMbld())activate();});
})();
