(() => {
  const SETTINGS_KEY='sscGeneralSettingsV1',LANGUAGE_KEY='sscLanguageV1',PREVIEW_SIZE_KEY='sscCubePreviewSizeV1';
  const defaults={textSize:100,font:'Rubik',timerFont:'Orbitron',timePrecision:3,theme:'light',primaryColor:'#2563eb'};
  const modal=document.getElementById('generalSettingsModal'),openButton=document.getElementById('generalSettingsButton'),closeButton=document.getElementById('closeGeneralSettings'),languageSelect=document.getElementById('languageSelect'),textSizeRange=document.getElementById('textSizeRange'),textSizeValue=document.getElementById('textSizeValue'),fontSelect=document.getElementById('fontSelect'),timerFontSelect=document.getElementById('timerFontSelect'),timePrecisionSelect=document.getElementById('timePrecisionSelect'),primaryColorInput=document.getElementById('primaryColorInput'),primaryColorValue=document.getElementById('primaryColorValue'),resetPrimaryColor=document.getElementById('resetPrimaryColor'),hiddenLanguageToggle=document.getElementById('languageToggle'),themeButtons=[...document.querySelectorAll('[data-theme-choice]')],cubeColorInputs=[...document.querySelectorAll('[data-cube-face]')],resetCubeColors=document.getElementById('resetCubeColors');
  const FONT_OPTIONS=[['Rubik','Rubik'],['Assistant','Assistant'],['Heebo','Heebo'],['Alef','Alef'],['NotoHebrew','Noto Sans Hebrew']],TIMER_FONT_OPTIONS=[['Orbitron','Orbitron'],['Audiowide','Audiowide'],['ShareTechMono','Share Tech Mono'],['Oxanium','Oxanium'],['ChakraPetch','Chakra Petch'],['system','System']];
  function injectMobileSettingsFix(){if(document.getElementById('sscMobileSettingsFix'))return;const style=document.createElement('style');style.id='sscMobileSettingsFix';style.textContent=`
    @media(max-width:700px){
      .settings-modal{padding:10px!important;align-items:center!important;overflow:auto!important;}
      .settings-dialog{width:min(96vw,520px)!important;max-width:96vw!important;max-height:92vh!important;overflow-y:auto!important;overflow-x:hidden!important;padding:16px!important;}
      .settings-dialog-head{position:sticky!important;top:-16px!important;z-index:5!important;background:var(--card-solid)!important;padding-top:4px!important;}
      .settings-dialog-head h2{font-size:clamp(24px,8vw,34px)!important;line-height:1.15!important;}
      .general-settings-grid{width:100%!important;min-width:0!important;gap:12px!important;}
      .general-setting-row{grid-template-columns:1fr!important;gap:7px!important;width:100%!important;min-width:0!important;padding:4px 0!important;}
      .general-setting-row>span{font-size:1em!important;font-weight:700!important;}
      .general-setting-row select,.range-control,.color-control,.theme-options,.cube-colors-control{width:100%!important;min-width:0!important;max-width:100%!important;}
      .range-control{grid-template-columns:minmax(0,1fr) 54px!important;}
      .range-control input{min-width:0!important;width:100%!important;}
      .color-control{grid-template-columns:52px minmax(0,1fr) auto!important;gap:8px!important;}
      .color-control output{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;}
      .cube-colors-control{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;}
      .cube-color-item{min-width:0!important;padding:8px 9px!important;overflow:hidden!important;}
      .cube-color-item span{white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;}
      .cube-color-item input{flex:0 0 34px!important;width:34px!important;height:30px!important;}
      .cube-colors-reset{width:100%!important;min-width:0!important;}
      .theme-options{grid-template-columns:repeat(3,minmax(0,1fr))!important;}
      .theme-options button{min-width:0!important;padding:9px 5px!important;}
    }
    @media(max-width:380px){
      .settings-dialog{padding:13px!important;}
      .cube-colors-control{grid-template-columns:1fr!important;}
      .color-control{grid-template-columns:46px minmax(0,1fr)!important;}
      .color-control button{grid-column:1/-1!important;width:100%!important;}
      .theme-options{grid-template-columns:1fr!important;}
    }
  `;document.head.appendChild(style)}
  function injectPreviewSizeStyles(){if(document.getElementById('sscPreviewSizeStyles'))return;const style=document.createElement('style');style.id='sscPreviewSizeStyles';style.textContent=`
    .flat-timer .cube-preview-card{width:var(--ssc-preview-width,116px)!important;min-width:var(--ssc-preview-width,116px)!important;height:var(--ssc-preview-height,76px)!important;min-height:var(--ssc-preview-height,76px)!important;}
    .flat-timer .cube-preview-net{--face:var(--ssc-preview-face,23px)!important;}
  `;document.head.appendChild(style)}
  function getPreviewSize(){const n=Number(localStorage.getItem(PREVIEW_SIZE_KEY));return Number.isFinite(n)?Math.min(250,Math.max(50,n)):100}
  function applyPreviewSize(){const scale=getPreviewSize()/100;let baseW=116,baseH=76,baseFace=23;if(innerWidth<=560){baseW=74;baseH=54;baseFace=14}else if(innerWidth<=900){baseW=92;baseH=64;baseFace=18}document.documentElement.style.setProperty('--ssc-preview-width',`${Math.round(baseW*scale)}px`);document.documentElement.style.setProperty('--ssc-preview-height',`${Math.round(baseH*scale)}px`);document.documentElement.style.setProperty('--ssc-preview-face',`${Math.max(8,Math.round(baseFace*scale))}px`);const range=document.getElementById('cubePreviewSizeRange'),output=document.getElementById('cubePreviewSizeValue');if(range)range.value=String(getPreviewSize());if(output)output.textContent=`${getPreviewSize()}%`}
  function initPreviewSizeControl(){if(document.getElementById('cubePreviewSizeRange'))return;const cubeColors=document.getElementById('cubeColorsSettingLabel')?.parentElement;if(!cubeColors)return;const row=document.createElement('label');row.className='general-setting-row';row.innerHTML=`<span id="cubePreviewSizeSettingLabel">גודל התצוגה</span><div class="range-control"><input id="cubePreviewSizeRange" type="range" min="50" max="250" step="10" value="100"><output id="cubePreviewSizeValue">100%</output></div>`;cubeColors.parentElement.insertBefore(row,cubeColors);const range=row.querySelector('#cubePreviewSizeRange');range.value=String(getPreviewSize());range.addEventListener('input',()=>{localStorage.setItem(PREVIEW_SIZE_KEY,String(Number(range.value)));applyPreviewSize()});applyPreviewSize()}
  function fillSelect(s,o,c){if(!s)return;s.innerHTML='';o.forEach(([v,l])=>{const x=document.createElement('option');x.value=v;x.textContent=l;s.appendChild(x)});s.value=o.some(([v])=>v===c)?c:o[0][0]}
  function repairSelectors(){if(languageSelect)languageSelect.innerHTML='<option value="he">עברית</option><option value="en">English</option>';fillSelect(fontSelect,FONT_OPTIONS,fontSelect?.value);fillSelect(timerFontSelect,TIMER_FONT_OPTIONS,timerFontSelect?.value)}
  function loadSettings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)),m={...defaults,...saved};if(!FONT_OPTIONS.some(([v])=>v===m.font))m.font=defaults.font;if(!TIMER_FONT_OPTIONS.some(([v])=>v===m.timerFont))m.timerFont=defaults.timerFont;if(![2,3].includes(Number(m.timePrecision)))m.timePrecision=3;return m}catch{return{...defaults}}}let settings=loadSettings();function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function fontStack(f){return f==='Assistant'?'"Assistant",sans-serif':f==='Heebo'?'"Heebo",sans-serif':f==='Alef'?'"Alef",sans-serif':f==='NotoHebrew'?'"Noto Sans Hebrew",sans-serif':'"Rubik",sans-serif'}function timerFontStack(f){return f==='Audiowide'?'"Audiowide",sans-serif':f==='ShareTechMono'?'"Share Tech Mono",monospace':f==='Oxanium'?'"Oxanium",sans-serif':f==='ChakraPetch'?'"Chakra Petch",sans-serif':f==='system'?'system-ui,-apple-system,"Segoe UI",sans-serif':'"Orbitron",sans-serif'}function validColor(v){return /^#[0-9a-f]{6}$/i.test(v)?v:defaults.primaryColor}
  function syncCubeColors(){if(!window.SSCCubePreview)return;const colors=window.SSCCubePreview.getColors();cubeColorInputs.forEach(i=>i.value=colors[i.dataset.cubeFace]||'#000000')}
  function applyAppearance(){const theme=['light','dark','oled'].includes(settings.theme)?settings.theme:'light';settings.primaryColor=validColor(settings.primaryColor);document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--font-scale',String((Number(settings.textSize)||100)/100));document.documentElement.style.setProperty('--app-font',fontStack(settings.font));document.documentElement.style.setProperty('--timer-font',timerFontStack(settings.timerFont));document.documentElement.style.setProperty('--accent',settings.primaryColor);themeButtons.forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));textSizeRange.value=String(settings.textSize||100);textSizeValue.textContent=`${settings.textSize||100}%`;fontSelect.value=settings.font||defaults.font;if(timerFontSelect)timerFontSelect.value=settings.timerFont||defaults.timerFont;if(timePrecisionSelect)timePrecisionSelect.value=String(settings.timePrecision);primaryColorInput.value=settings.primaryColor;primaryColorValue.textContent=settings.primaryColor.toUpperCase();syncCubeColors();applyPreviewSize()}
  function currentLanguage(){return localStorage.getItem(LANGUAGE_KEY)==='en'?'en':'he'}
  function updateLabels(){const en=currentLanguage()==='en';const set=(id,a,b)=>{const e=document.getElementById(id);if(e)e.textContent=en?a:b};set('generalSettingsTitle','General settings','הגדרות כלליות');set('languageSettingLabel','Language','שפה');set('textSizeSettingLabel','Text size','גודל הטקסט');set('fontSettingLabel','Text font','גופן הטקסט');set('timerFontSettingLabel','Timer font','גופן הטיימר');set('timePrecisionSettingLabel','Time precision','דיוק הזמן');set('primaryColorSettingLabel','Primary color','צבע ראשי');set('cubePreviewSizeSettingLabel','Preview size','גודל התצוגה');set('cubeColorsSettingLabel','Cube colors','צבעי הקובייה');set('cubeWhiteLabel','White','לבן');set('cubeYellowLabel','Yellow','צהוב');set('cubeGreenLabel','Green','ירוק');set('cubeBlueLabel','Blue','כחול');set('cubeRedLabel','Red','אדום');set('cubeOrangeLabel','Orange','כתום');set('resetCubeColors','Reset cube colors','איפוס צבעי קובייה');set('themeSettingLabel','Theme','עיצוב');set('themeLightButton','Light','בהיר');set('themeDarkButton','Dark','כהה');resetPrimaryColor.textContent=en?'Reset':'איפוס';closeButton.setAttribute('aria-label',en?'Close':'סגור');openButton.title=en?'General settings':'הגדרות כלליות';openButton.setAttribute('aria-label',openButton.title);languageSelect.value=en?'en':'he'}
  function openModal(){modal.hidden=false;updateLabels();syncCubeColors();applyPreviewSize();requestAnimationFrame(()=>closeButton.focus())}function closeModal(){modal.hidden=true;openButton.focus()}
  injectMobileSettingsFix();injectPreviewSizeStyles();initPreviewSizeControl();repairSelectors();openButton.addEventListener('click',openModal);closeButton.addEventListener('click',closeModal);modal.querySelector('[data-close-settings]').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});window.addEventListener('resize',applyPreviewSize);languageSelect.addEventListener('change',()=>{if(languageSelect.value!==currentLanguage())hiddenLanguageToggle.click();updateLabels()});textSizeRange.addEventListener('input',()=>{settings.textSize=Number(textSizeRange.value);saveSettings();applyAppearance()});fontSelect.addEventListener('change',()=>{settings.font=fontSelect.value;saveSettings();applyAppearance()});timerFontSelect?.addEventListener('change',()=>{settings.timerFont=timerFontSelect.value;saveSettings();applyAppearance()});timePrecisionSelect?.addEventListener('change',()=>{settings.timePrecision=Number(timePrecisionSelect.value);saveSettings();applyAppearance();window.dispatchEvent(new Event('ssc-time-precision-change'))});primaryColorInput.addEventListener('input',()=>{settings.primaryColor=primaryColorInput.value;saveSettings();applyAppearance()});resetPrimaryColor.addEventListener('click',()=>{settings.primaryColor=defaults.primaryColor;saveSettings();applyAppearance()});themeButtons.forEach(b=>b.addEventListener('click',()=>{settings.theme=b.dataset.themeChoice;saveSettings();applyAppearance()}));cubeColorInputs.forEach(input=>input.addEventListener('input',()=>{if(!window.SSCCubePreview)return;const colors=window.SSCCubePreview.getColors();colors[input.dataset.cubeFace]=input.value;window.SSCCubePreview.setColors(colors)}));resetCubeColors?.addEventListener('click',()=>{window.SSCCubePreview?.resetColors();syncCubeColors()});applyAppearance();updateLabels();
})();