(()=>{
  'use strict';
  const HISTORY_KEY='rubiksCubeTimerHistoryV1',STATE_KEY='sscTrainingStateV1',GOALS_KEY='sscTrainingGoalsV1',LANGUAGE_KEY='sscLanguageV1';
  const cases=()=>window.SSCTrainingCases||[];
  const parse=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback;}catch{return fallback;}};
  const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const he=()=>localStorage.getItem(LANGUAGE_KEY)!=='en';
  const tx=(hebrew,english)=>he()?hebrew:english;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=ms=>Number.isFinite(ms)?(ms/1000).toFixed(2):'DNF';
  const effective=s=>s.penalty==='DNF'?Infinity:Number(s.rawTimeMs||s.timeMs||0)+(s.penalty==='+2'?2000:0);
  const history=()=>parse(HISTORY_KEY,[]);
  let state={mode:'normal',trainer:'pll',filter:'all',selected:[],favorites:[],hideName:true,showAlgorithm:false,crossColor:'white',currentCaseId:null,practice:null,...parse(STATE_KEY,{})};
  let pendingReviewId=null;
  const persist=()=>save(STATE_KEY,state);
  const attempts=()=>history().filter(s=>s.training||s.practice);
  const caseAttempts=id=>history().filter(s=>s.training?.caseId===id);
  const mean=list=>{const values=list.map(effective).filter(Number.isFinite);return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
  const deviation=list=>{const values=list.map(effective).filter(Number.isFinite);if(values.length<2)return null;const avg=values.reduce((a,b)=>a+b,0)/values.length;return Math.sqrt(values.reduce((sum,v)=>sum+((v-avg)**2),0)/values.length);};
  const ao=(list,n)=>{if(list.length<n)return null;const values=list.slice(0,n).map(effective).sort((a,b)=>a-b);if(values.filter(Number.isFinite).length<n-1)return Infinity;return values.slice(1,-1).reduce((a,b)=>a+b,0)/(n-2);};
  function caseStats(id){const list=caseAttempts(id),valid=list.map(effective).filter(Number.isFinite),reviewed=list.filter(s=>s.training?.success!==null&&s.training?.success!==undefined);return{attempts:list.length,best:valid.length?Math.min(...valid):null,mean:mean(list),ao5:ao(list,5),success:reviewed.length?reviewed.filter(s=>s.training.success).length/reviewed.length:null,recognition:list.filter(s=>s.training?.errorType==='recognition').length,execution:list.filter(s=>s.training?.errorType==='execution').length};}
  function weakScore(item){const s=caseStats(item.id);if(!s.attempts)return 100;const failure=s.success===null?25:(1-s.success)*55;const scarcity=Math.max(0,8-s.attempts)*4;const errors=(s.recognition*5)+(s.execution*3);const speed=s.mean?Math.min(25,s.mean/180):0;return failure+scarcity+errors+speed;}
  function activeCases(){let list=cases().filter(c=>c.category===state.trainer);if(state.filter==='selected')list=list.filter(c=>state.selected.includes(c.id));if(state.filter==='favorites')list=list.filter(c=>state.favorites.includes(c.id));if(state.filter==='untrained')list=list.filter(c=>!caseStats(c.id).attempts);if(state.filter==='weak')list=[...list].sort((a,b)=>weakScore(b)-weakScore(a)).slice(0,Math.max(1,Math.min(10,list.length)));return list.length?list:cases().filter(c=>c.category===state.trainer);}
  const randomAUF=()=>['','U',"U'",'U2'][Math.floor(Math.random()*4)];
  function pickCase(){const list=activeCases(),item=list[Math.floor(Math.random()*list.length)];state.currentCaseId=item?.id||null;persist();return item;}
  function currentCase(){return cases().find(c=>c.id===state.currentCaseId)||null;}
  function setMode(mode){state.mode=mode;pendingReviewId=null;if(mode==='pll'||mode==='oll'){state.trainer=mode;state.currentCaseId=null;}persist();document.documentElement.dataset.trainingMode=mode==='normal'?'off':'on';render();if(mode!=='normal')window.SSCTimerEvents?.setCurrent?.('333').then(()=>window.SSCTimerEvents?.newScramble?.());}
  async function nextScramble(){if(state.mode==='normal')return null;if(state.mode==='practice')return state.practice?.scramble||null;if(state.mode==='cross')return window.SSCScrambles?.generate?.('333');if(state.mode==='pll'||state.mode==='oll'){const item=pendingReviewId?currentCase():pickCase();if(!item)return null;const auf=state.mode==='pll'?randomAUF():'';return [auf,item.setup].filter(Boolean).join(' ');}return null;}
  function consumeAttemptMetadata(){if(state.mode==='normal')return{};if(state.mode==='practice')return{practice:true,practiceGroupId:state.practice?.originalId,training:{type:'practice',success:null}};if(state.mode==='cross')return{practice:true,training:{type:'cross',crossColor:state.crossColor,success:null}};const item=currentCase();return{practice:true,training:{type:state.mode,caseId:item?.id||null,success:null}};}
  function startPractice(solve){state.practice={originalId:solve.id,scramble:solve.scramble,eventId:solve.eventId||'333',startedAt:new Date().toISOString()};state.mode='practice';persist();render();window.SSCTimerEvents?.setCurrent?.(state.practice.eventId).then(()=>window.SSCTimerEvents?.repeatScramble?.(state.practice.scramble,state.practice.eventId));}
  function review(id,type){const all=history(),index=all.findIndex(s=>s.id===id);if(index<0)return;all[index].training={...(all[index].training||{}),success:type==='correct',errorType:type==='recognition'||type==='execution'?type:type==='mistake'?'mistake':null};save(HISTORY_KEY,all);pendingReviewId=null;window.dispatchEvent(new StorageEvent('storage',{key:HISTORY_KEY,newValue:localStorage.getItem(HISTORY_KEY),storageArea:localStorage}));render();window.SSCTimerEvents?.newScramble?.();}
  function practiceList(){return history().filter(s=>s.practice&&s.practiceGroupId===state.practice?.originalId).reverse();}
  function metricForGoal(goal){const normal=history().filter(s=>!s.practice&&!s.training&&(goal.event==='all'||!goal.event||s.eventId===goal.event));const clean=s=>s.penalty==='OK';switch(goal.metric){case'single':return normal.filter(s=>effective(s)<goal.threshold*1000).length;case'ao5':return ao(normal,5)!==null&&ao(normal,5)<goal.threshold*1000?1:0;case'ao12':return ao(normal,12)!==null&&ao(normal,12)<goal.threshold*1000?1:0;case'solveCount':return normal.length;case'cleanStreak':return streak(normal,clean);case'noDnf':return streak(normal,s=>s.penalty!=='DNF');case'noPlus2':return streak(normal,s=>s.penalty!=='+2');case'trainingAttempts':return history().filter(s=>s.training?.caseId&&(goal.caseId?goal.caseId===s.training.caseId:true)).length;case'trainingSuccess':{const list=history().filter(s=>s.training?.caseId&&(goal.caseId?goal.caseId===s.training.caseId:true)&&s.training.success!==null);return list.length?Math.round(list.filter(s=>s.training.success).length/list.length*100):0;}default:return 0;}}
  function streak(list,test){let count=0;for(const solve of list){if(!test(solve))break;count++;}return count;}
  function goals(){return parse(GOALS_KEY,[]);}
  function addGoal(metric,target,threshold,event,caseId){const list=goals();list.push({id:crypto.randomUUID?.()||String(Date.now()),metric,target:Number(target)||1,threshold:Number(threshold)||0,event:event||'333',caseId:caseId||'',createdAt:new Date().toISOString()});save(GOALS_KEY,list);render();}
  function removeGoal(id){save(GOALS_KEY,goals().filter(g=>g.id!==id));render();}
  function goalLabel(g){const labels={single:tx('פתרונות מתחת ליעד','Solves under target'),ao5:'Ao5',ao12:'Ao12',solveCount:tx('מספר פתרונות','Solve count'),cleanStreak:tx('רצף נקי','Clean streak'),noDnf:tx('רצף ללא DNF','No DNF streak'),noPlus2:tx('רצף ללא +2','No +2 streak'),trainingAttempts:tx('ניסיונות אימון','Training attempts'),trainingSuccess:tx('אחוז הצלחה באימון','Training success')};return labels[g.metric]||g.metric;}
  function recentSummary(){const list=attempts().slice(0,30);if(!list.length)return tx('עדיין אין נתוני אימון','No training data yet');const type=list[0].training?.type||'practice',same=list.filter(s=>(s.training?.type||'practice')===type);return `${type.toUpperCase()} · ${same.length} ${tx('ניסיונות','attempts')} · Best ${fmt(Math.min(...same.map(effective)))}`;}
  function recommendation(){const trained=cases().filter(c=>caseStats(c.id).attempts>=3).sort((a,b)=>weakScore(b)-weakScore(a));if(trained.length){const c=trained[0],s=caseStats(c.id);return `${tx('כדאי לתרגל','Practice')} ${c.name} · ${s.success===null?'—':Math.round(s.success*100)+'%'}`;}return tx('השלם לפחות 3 ניסיונות כדי לקבל המלצה','Complete at least 3 attempts for a recommendation');}
  function ensureUi(){if(document.getElementById('trainingButton'))return;const button=document.createElement('button');button.id='trainingButton';button.className='toolbar-button';button.type='button';button.innerHTML='<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6.5 6.5h11v11h-11z"/><path d="M9 3v3.5M15 3v3.5M9 17.5V21M15 17.5V21M3 9h3.5M3 15h3.5M17.5 9H21M17.5 15H21"/><path d="m9.5 12 1.7 1.7 3.5-3.7"/></svg><span>TRAINING</span>';button.setAttribute('aria-label',tx('אימון','Training'));button.title=tx('אימון','Training');document.querySelector('.topbar-start')?.appendChild(button);const modal=document.createElement('div');modal.id='trainingModal';modal.className='settings-modal training-modal';modal.hidden=true;modal.innerHTML='<div class="settings-backdrop" data-training-close></div><section class="settings-dialog training-dialog"><div class="settings-dialog-head"><h2 id="trainingTitle"></h2><button class="modal-close" data-training-close type="button">×</button></div><div id="trainingContent"></div></section>';document.body.appendChild(modal);button.addEventListener('click',()=>{modal.hidden=false;render();});modal.querySelectorAll('[data-training-close]').forEach(el=>el.addEventListener('click',()=>modal.hidden=true));modal.addEventListener('click',handleClick);modal.addEventListener('change',handleChange);}
  function dashboard(){const weak=cases().filter(c=>caseStats(c.id).attempts).sort((a,b)=>weakScore(b)-weakScore(a)).slice(0,4);const active=goals().slice(0,4);return `<div class="training-quick"><button data-start="pll">PLL</button><button data-start="oll">OLL</button><button data-start="cross">Cross</button><button data-practice-last>${tx('ערבוב אחרון','Last scramble')}</button></div><div class="training-grid"><article><h3>${tx('מקרים חלשים','Weak Cases')}</h3>${weak.length?weak.map(c=>`<p><strong>${esc(c.name)}</strong><span>${fmt(caseStats(c.id).mean)} · ${Math.round((caseStats(c.id).success||0)*100)}%</span></p>`).join(''):`<small>${tx('אין מספיק נתונים','Not enough data')}</small>`}</article><article><h3>${tx('מטרות פעילות','Active Goals')}</h3>${active.length?active.map(g=>goalRow(g)).join(''):`<small>${tx('אין מטרות פעילות','No active goals')}</small>`}<button data-goal-new>${tx('מטרה חדשה','New goal')}</button></article><article><h3>${tx('אימון אחרון','Recent Training')}</h3><p>${esc(recentSummary())}</p></article><article><h3>${tx('המלצה','Recommended Practice')}</h3><p>${esc(recommendation())}</p></article></div>`;}
  function goalRow(g){const current=metricForGoal(g),target=g.target,pct=Math.min(100,Math.round(current/target*100));return `<div class="goal-row"><div><strong>${esc(goalLabel(g))}</strong><span>${current} / ${target}</span></div><progress max="100" value="${pct}"></progress><button data-goal-delete="${esc(g.id)}">×</button></div>`;}
  function trainer(){const item=currentCase(),s=item?caseStats(item.id):null;return `<div class="trainer-toolbar"><button data-back>← ${tx('אימון','Training')}</button><select data-filter><option value="all">All</option><option value="selected">Selected</option><option value="weak">Weak</option><option value="favorites">Favorites</option><option value="untrained">Untrained</option></select><button data-cases>${tx('בחירת מקרים','Cases')}</button></div><div class="case-card"><div class="case-kicker">${state.trainer.toUpperCase()}</div><h3>${!item?tx('מייצר מקרה…','Generating case…'):state.hideName&&!pendingReviewId?'?':esc(item.name)}</h3><div class="case-alg" ${state.showAlgorithm||pendingReviewId?'':'hidden'}>${esc(item?.alg||'')}</div><div class="case-actions"><button data-reveal>${tx('חשיפה','Reveal')}</button><button data-toggle-alg>${tx('הצג אלגוריתם','Show Algorithm')}</button><button data-favorite class="${item&&state.favorites.includes(item.id)?'active':''}">★</button></div>${s?`<div class="case-stats"><span>${s.attempts} Attempts</span><span>Best ${fmt(s.best)}</span><span>Mean ${fmt(s.mean)}</span><span>Ao5 ${fmt(s.ao5)}</span><span>${s.success===null?'—':Math.round(s.success*100)+'%'} Success</span><span>R ${s.recognition} / E ${s.execution}</span></div>`:''}</div>${pendingReviewId?reviewButtons():''}`;}
  function reviewButtons(){return `<div class="review-actions"><button data-review="correct">${tx('נכון','Correct')}</button><button data-review="mistake">${tx('טעות','Mistake')}</button><button data-review="recognition">${tx('טעות זיהוי','Recognition Error')}</button><button data-review="execution">${tx('טעות ביצוע','Execution Error')}</button></div>`;}
  function cross(){const stats=history().filter(s=>s.training?.type==='cross');return `<div class="trainer-toolbar"><button data-back>← ${tx('אימון','Training')}</button></div><div class="case-card"><div class="case-kicker">CROSS TRAINER</div><h3>${tx('תכנון Cross','Plan Cross')}</h3><label>${tx('צבע Cross','Cross color')}<select data-cross-color>${['white','yellow','green','blue','red','orange'].map(v=>`<option value="${v}" ${v===state.crossColor?'selected':''}>${v}</option>`).join('')}</select></label><div class="case-stats"><span>${stats.length} Attempts</span><span>Best ${fmt(stats.length?Math.min(...stats.map(effective)):null)}</span><span>Mean ${fmt(mean(stats))}</span><span>${Math.round((stats.filter(s=>s.training.success).length/Math.max(1,stats.filter(s=>s.training.success!==null).length))*100)}% Success</span><span>${tx('עקביות','Consistency')} ±${fmt(deviation(stats))}</span></div></div>${pendingReviewId?reviewButtons():''}`;}
  function practice(){const list=practiceList(),original=history().find(s=>s.id===state.practice?.originalId),first=list[0],best=list.length?Math.min(...list.map(effective)):null,improved=first&&Number.isFinite(best)?effective(first)-best:0;return `<div class="trainer-toolbar"><button data-exit-practice>${tx('יציאה מתרגול','Exit Practice')}</button></div><div class="case-card"><div class="case-kicker">PRACTICE</div><h3>${tx('תרגול אותו ערבוב','Repeat Scramble')}</h3><p class="practice-scramble">${esc(state.practice?.scramble||'')}</p><div class="practice-attempts">${list.map((s,i)=>`<span>Attempt ${i+1}</span><strong>${fmt(effective(s))}</strong>`).join('')||`<small>${tx('התחל את הניסיון הראשון','Start the first attempt')}</small>`}</div>${list.length>1?`<div class="improvement">${tx('שיפור','Improved by')} ${fmt(improved)}</div>`:''}<small>${tx('הפתרון המקורי נשמר ללא שינוי','Original solve remains unchanged')} · ${fmt(original?effective(original):null)}</small></div>`;}
  function casesPicker(){const list=cases().filter(c=>c.category===state.trainer);return `<div class="picker"><h3>${tx('בחירת מקרים','Select Cases')}</h3><div class="case-picker-list">${list.map(c=>`<label><input type="checkbox" data-case-id="${c.id}" ${state.selected.includes(c.id)?'checked':''}><span>${esc(c.name)}</span><button type="button" data-case-favorite="${c.id}">${state.favorites.includes(c.id)?'★':'☆'}</button></label>`).join('')}</div><button data-picker-done>${tx('סיום','Done')}</button></div>`;}
  function goalForm(){return `<form id="goalForm" class="goal-form"><h3>${tx('מטרה חדשה','New Goal')}</h3><select name="metric">${['single','ao5','ao12','solveCount','cleanStreak','noDnf','noPlus2','trainingAttempts','trainingSuccess'].map(v=>`<option value="${v}">${v}</option>`).join('')}</select><label>${tx('יעד','Target')}<input name="target" type="number" min="1" value="10" required></label><label>${tx('סף זמן/אחוז','Time threshold / percent')}<input name="threshold" type="number" min="0" step="0.01" value="20"></label><select name="event"><option value="333">3×3</option><option value="222">2×2</option><option value="all">All</option></select><button type="submit">${tx('צור מטרה','Create Goal')}</button><button type="button" data-goal-cancel>${tx('ביטול','Cancel')}</button></form>`;}
  function render(view){ensureUi();const modal=document.getElementById('trainingModal'),host=document.getElementById('trainingContent');document.getElementById('trainingTitle').textContent=tx('אימון','Training');if(!host)return;if(view==='cases')host.innerHTML=casesPicker();else if(view==='goal')host.innerHTML=goalForm();else if(state.mode==='pll'||state.mode==='oll')host.innerHTML=trainer();else if(state.mode==='cross')host.innerHTML=cross();else if(state.mode==='practice')host.innerHTML=practice();else host.innerHTML=dashboard();const filter=host.querySelector('[data-filter]');if(filter)filter.value=state.filter;modal?.querySelector('#goalForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);addGoal(d.get('metric'),d.get('target'),d.get('threshold'),d.get('event'),d.get('caseId'));render();});}
  function handleClick(event){const el=event.target.closest('button');if(!el)return;if(el.dataset.start)setMode(el.dataset.start);else if(el.hasAttribute('data-back'))setMode('normal');else if(el.hasAttribute('data-cases'))render('cases');else if(el.hasAttribute('data-picker-done'))render();else if(el.hasAttribute('data-reveal')){pendingReviewId=pendingReviewId||'reveal';render();}else if(el.hasAttribute('data-toggle-alg')){state.showAlgorithm=!state.showAlgorithm;persist();render();}else if(el.hasAttribute('data-favorite')){const id=currentCase()?.id;if(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(v=>v!==id):[...state.favorites,id];persist();render();}}else if(el.dataset.caseFavorite){const id=el.dataset.caseFavorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(v=>v!==id):[...state.favorites,id];persist();render('cases');}else if(el.dataset.review&&pendingReviewId)review(pendingReviewId,el.dataset.review);else if(el.hasAttribute('data-exit-practice')){state.practice=null;setMode('normal');window.SSCTimerEvents?.newScramble?.();}else if(el.hasAttribute('data-goal-new'))render('goal');else if(el.hasAttribute('data-goal-cancel'))render();else if(el.dataset.goalDelete)removeGoal(el.dataset.goalDelete);else if(el.hasAttribute('data-practice-last')){const last=history().find(s=>!s.practice&&!s.training);if(last)startPractice(last);}}
  function handleChange(event){const el=event.target;if(el.matches('[data-filter]')){state.filter=el.value;state.currentCaseId=null;persist();render();window.SSCTimerEvents?.newScramble?.();}else if(el.matches('[data-cross-color]')){state.crossColor=el.value;persist();render();}else if(el.matches('[data-case-id]')){state.selected=el.checked?[...new Set([...state.selected,el.dataset.caseId])]:state.selected.filter(v=>v!==el.dataset.caseId);persist();}}
  window.addEventListener('ssc-solve-added',event=>{if(event.detail?.solve?.training){pendingReviewId=event.detail.solve.id;render();}});
  window.SSCTraining={nextScramble,consumeAttemptMetadata,startPractice,setMode,shouldInspect:()=>state.mode==='cross',getState:()=>({...state}),getCaseStats:caseStats,recalculateWeakCases:()=>cases().map(c=>({caseId:c.id,score:weakScore(c)})).sort((a,b)=>b.score-a.score)};
  ensureUi();document.documentElement.dataset.trainingMode=state.mode==='normal'?'off':'on';render();
})();
